service:
- docker

env:
  global:
  - TERM=dumb
  - secure: fhZqFbbvRCRWF+xcWQzQnbnzVp378lxKsvvfTzDf443kNoS3d424jY07uWacjGwScCR3mPb/X8Zxleuq73obOAMv33gciqh8UJteyPuUwB/NQIDwyDIt9J2U/xOobZPLuUdc+J48uxmrpr4geTb2gK4FvzKcHu46ZAaRXTlr2KAdIVXh2gH45psP7xEeVDCW4qxoG09vGMvR+VvLoe/79qi1VK/t+Ldmtfl7apPVhoZYpRhNXQ9l0vQjd6mMezy/AGNFLinKM9PaXZo+V/WAL7FQuopuBrJNZZyJpIdfLlczSd+6zRnMJYbFPMogOEJwPsDCrrQNalBdtGy62XhGeR4CjNWAaJs/cCkrjfMjxn+7sfbvl7fseL6QHoosd88x6NiGftAp6rO9TswhPcOnuE983R5ViG56mwF/kJYfaVezwQ74naLN7J6lADiqV7ULBO7mGVftzPXa2XAj/+pcjDDk36YMALXC+ZlIuhMW+GZY5PjtTJLylOm32sxCJzPBBFxIPpa0I/ANHiH7mVC3WhopTM5adCrPdv8OwTbMlwtkhSLzTiaEEe+qBx6K5v2OzqBPvbrIHMFyPwBS8oVlZPpw22d7No7gh07AT7FGvAok5qJX0+0sg65SaSW/obgn6SXzyf0FFh8lXrjquDmE0rchxa1q4aBiIOM+B3plRRI=

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - python-pip
  - docker-ce

install: true
before_script:
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80 8080 80

script:
- |
  function create_some_files {
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    echo "" >> /tmp/camel-in/"${RANDOM}.txt"
    sleep 2
    return 0
  }
#
- bash gradlew >/dev/null
- java -jar ./build/libs/*.jar &
- wait_for 8080
- create_some_files
- stop_any 8080 80 8080 80
- ls /tmp/camel-out/
- rm /tmp/camel-out/*
#
- bash ./build/libs/*.jar &
- wait_for 8080
- create_some_files
- stop_any 8080 80 8080 80
- ls /tmp/camel-out/
- rm /tmp/camel-out/*
# docker tests not properly working in travis (try dind if you really need it)
- bash gradlew composeUp
- create_some_files
- CONTAINER_ID=$(docker ps|awk '{print $1}'|grep -v CONTAINER)
- docker cp ${CONTAINER_ID}:/tmp/camel-out /tmp/camel-gradle
- ls /tmp/camel-gradle
- bash gradlew composeDown
- stop_any 8080 80 8080 80
- rm /tmp/camel-out/*
#
- bash mvnw >/dev/null
- java -jar ./target/*.jar &
- wait_for 8080
- create_some_files
- stop_any 8080 80 8080 80
- ls /tmp/camel-out/
- rm /tmp/camel-out/*
#
- bash ./target/*.jar &
- wait_for 8080
- create_some_files
- stop_any 8080 80 8080 80
- ls /tmp/camel-out/
- rm /tmp/camel-out/*
#
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up -P docker -Ddetails=true
- sleep 30
- create_some_files
- CONTAINER_ID=$(docker ps|awk '{print $1}'|grep -v CONTAINER)
- docker cp ${CONTAINER_ID}:/tmp/camel-out /tmp/camel-maven
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker
- stop_any 8080 80 8080 80
- ls /tmp/camel-maven/

before_deploy: ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages

before_cache:
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
