env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - wget
  - unzip

install: true
before_script:

script:
- ./gradlew -S >/dev/null
#
- ./gradlew clean check
- cat ./build/findbugs/main.html | wc -l
#
- ./mvnw >/dev/null
- ./mvnw clean verify site
- cat ./target/site/findbugs.html | wc -l
# WTF?
- ./gradlew :docs:tasks --all
- ./gradlew :docs:asciidoctor
- ./gradlew :docs:documentation
#
- wget https://services.gradle.org/distributions/gradle-4.8-bin.zip
- unzip -d /tmp gradle-4.8-bin.zip
- export PATH="/tmp/gradle-4.8/bin:$PATH"
- gradle :docs:documentation

cache:
  directories:
  - ${HOME}/.m2
  - ${HOME}/.gradle
