version: "2.1"

services:

  gradle-apache-camel-spring-boot-1-x-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes:
    - "/tmp/camel-in:/tmp/camel-in:rw"
    - "/tmp/camel-out:/tmp/camel-out:rw"
    - "/tmp/camel-jms-in:/tmp/camel-jms-in:rw"
    - "/tmp/camel-jms-out:/tmp/camel-jms-out:rw"
    ports: ["8080:8080"]
    networks: [backing-services]
    restart: unless-stopped

networks:
  backing-services:
    driver: bridge
