= {root-project-name} ({project-version})
////
image:https://travis-ci.org/user-name-change-me/project-name-change-me.svg?branch=master["Build Status", link={github-url}]
image:https://gitlab.com/user-name-change-me/project-name-change-me/badges/master/build.svg["Build Status", link={gitlab-url}]
image:https://img.shields.io/bitbucket/pipelines/user-name-change-me/project-name-change-me.svg["Build Status", link={bitbucket-url}]
////
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]

//GitLab CI status:
//image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]
//
//BitBucket pipeline status:
//image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]

== Introduction

include::../../README.adoc[tags=content]

== Implementation

=== camel spring configuration

.src/main/resources/application.properties
[source,properties]
----
include::../../src/main/resources/application.properties[tags=content]
----

=== move all files from directory

source directory: `/tmp/camel-in/`
destination directory: `/tmp/camel-out/`

.src/main/java/daggerok/app/MoveFilesCamelConfig.java
[source,java]
----
include::../../src/main/java/daggerok/app/MoveFilesCamelConfig.java[tags=move-files]
----

=== move files via jms

source directory: `/tmp/camel-jms-in/`
process queue: `files`
destination directory: `/tmp/camel-jms-out/`

.move files via jms queue `jms:queue:files`
[source,java]
----
include::../../src/main/java/daggerok/app/MoveFilesViaJmsCamelConfig.java[tags=move-files-via-jms]
----

.jms component customizer
[source,java]
----
include::../../src/main/java/daggerok/app/MoveFilesViaJmsCamelConfig.java[tags=jms-component-customizer]
----

=== change filename by using camel header

source directory: `/tmp/camel-filename-in/`
destination directory: `/tmp/camel-filename-out/`

.setup camel header to change output filename in pattern: `uuid-changed.txt`
[source,java]
----
include::../../src/main/java/daggerok/app/ChangeFilenameHeaderCamelConfig.java[tags=change-filename-header]
----

=== process exchange

source directory: `/tmp/camel-exchange-in/`
destination directory: `/tmp/camel-exchange-out/`

.man in a middle: do additional stuff with message during camel pipeline (for instance, log message body):
[source,java]
----
include::../../src/main/java/daggerok/app/ExchangeProcessorCamelConfig.java[tags=process-exchange]
----

== BOM

.maven
[source,xml]
----
include::../../pom.xml[tags=content]
----

.gradle
[source,groovy]
----
include::../../gradle/spring-boot.gradle[tags=content]
----

== Links

ifdef::backend-html5[link:./index.pdf[Documentation in PFD format]]

link:{github-url}[GitHub repo]
link:https://daggerok.github.io/{root-project-name}[GitHub pages]

//link:{gitlab-url}[GitLab repo]
//link:https://daggerok.gitlab.io/{root-project-name}[GitLab pages]
//
//link:{bitbucket-url}[BitBucket repo]
